services:
  web:
    container_name: web
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        NODE_ENV: $NODE_ENV
    ports:
      - 3000:3000
    volumes:
      - ../src:/usr/src/app/src
      - ../public:/usr/src/app/public
    networks:
      - backend
    command: $RUN_COMMAND
  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - backend

networks:
  backend:
    name: backend